### ISSUE TITLE
2.3.0 is braking change and should be bumped to 3.0.0

### ISSUE THREAD

**Issue by vorg** [jwagner/simplex-noise.js#12]
I'm making a game where I was using use 2.2.0 to generate a terrain. After new `npm install` I've got recently published 2.3.0 and the resulting noise has changed breaking my landscape completely. To follow the semantic versioning I would suggest reverting the changes and publishing 2.4 that's backwards compatible and publishing permutation table as 3.0.0

Before 
<img width="1198" alt="screen shot 2017-01-12 at 21 00 06" src="https://cloud.githubusercontent.com/assets/171001/21908154/88479d8a-d90a-11e6-8c67-ff0bdc551108.png">

After
<img width="1200" alt="screen shot 2017-01-12 at 21 00 49" src="https://cloud.githubusercontent.com/assets/171001/21908159/8be97bde-d90a-11e6-986d-b4c1d7c47b55.png">

**Comment by jwagner** [comment]
First of all: Sorry for braking your game. 

Regarding the versioning: As far as I know, the version is referring to the **API** of the library. Not it's exact inner workings. That was my reasoning for not releasing a new major version.

In retrospective that's not very clever given that many applications rely on the same seed yielding the same output. I totally agree with that.

But following that reasoning it would be wrong to release a 2.4 that changes the output **again**.

So I think the best and most correct thing I can do at this point is to add a note to the README.

**Comment by vorg** [comment]
Ok, I hardcoded 2.2 in my app then. Thanks.
