### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by JosefKuchar** [jwagner/simplex-noise.js#13]
Hi, 
can you create definition file (.d.ts) for this simplex noise? :)

**Comment by jwagner** [comment]
I don't use typescript so I won't create a typescript definition file.
If you provide one I will include it in the next release though. :)

**Comment by Neonit** [comment]
The following should do the job. If included in the package, it should be in a file named `index.d.ts` in the package root. If one wants to add it manually, put it also in a file named `index.d.ts` in a folder named `simplex-noise` in another folder either included automatically by your Typescript compiler or referenced in your `typeRoots` option in the `tsconfig.json`. Of course, one can also put it anywhere and include it manually via `<reference>`.

```typescript
// Type definitions for simplex-noise 2.3.0
declare module 'simplex-noise'
{
	export = SimplexNoise;

	/** Deterministic simplex noise generator suitable for 2D, 3D and 4D spaces. */
	class SimplexNoise
	{
		/**
		 * Creates a new `SimplexNoise` instance. You want to use this sparingly, as it is a relatively
		 * expensive.
		 * @param {SimplexNoise.RandomNumberGenerator} [random=Math.random] - The random number
		 *     generator to use. This argument could e.g. be used to inject a seeded generator.
		 */
		constructor(random?: SimplexNoise.RandomNumberGenerator);

		/**
		 * Calculates the noise value in the range [-1;1] for the given point in a 2D space.
		 * @param {number} x
		 * @param {number} y
		 * @return {number}
		 */
		noise2D(x: number, y: number): number;

		/**
		 * Calculates the noise value in the range [-1;1] for the given point in a 3D space.
		 * @param {number} x
		 * @param {number} y
		 * @param {number} z
		 * @return {number}
		 */
		noise3D(x: number, y: number, z: number): number;

		/**
		 * Calculates the noise value in the range [-1;1] for the given point in a 4D space.
		 * @param {number} x
		 * @param {number} y
		 * @param {number} z
		 * @param {number} w
		 * @return {number}
		 */
		noise4D(x: number, y: number, z: number, w: number): number;
	}

	namespace SimplexNoise
	{
		export type RandomNumberGenerator = {(): number};
	}
}
```

**Comment by jwagner** [comment]
Hello @Neonit, thank you for your contribution. I've added the file to the repository and I would greatly appreciate it if you could have a quick look to make sure I haven't messed up.

**Comment by Neonit** [comment]
I cloned the repo as is and ran a quick and sloppy test. Worked as intended.

**Comment by jwagner** [comment]
Thank you!
