### ISSUE TITLE
can not use seeds

### ISSUE THREAD

**Issue by LittleSatan** [jwagner/simplex-noise.js#15]
if you try to use seeds ("var simplex = new SimplexNoise(Math.random);") the script will stop with an error.

**Comment by jwagner** [comment]
Please provide a complete script to reproduce the problem, including the versions that you are using.
The custom random function case is covered by tests and in general works.

**Comment by jwagner** [comment]
@LittleSatan any update on this?

**Comment by DavisMiculis** [comment]
I have similar problem, with custom random functions not working.

I'm currently using Phaser.js and this library. Here,s example code:
```
this.rand = new Phaser.RandomDataGenerator(['1234'])
this.simplex = new SimplexNoise(this.rand.normal) // rand.normal() is a function that returns random from 0.0 to 1.0
```

Gives error: `this.frac is not a function`, well the error is useless, because this.frac is property of Phaser random data generator. There's something going on with class inheritance, the `this` variable?

Another example using Chance.js:
```
this.chance = new Chance('12345');
this.simplex = new SimplexNoise(this.chance.random) // chance.random() is a function that returns random from 0.0 to 1.0
```

Although `Math.random` works fine.

**Comment by LittleSatan** [comment]
@jwagner i think the problem is solved. like you pointed out in the push request i misunderstood something. I am really sorry for wasting your time with this. 

@DavisMiculis It seems that you should use a PRNG like alea. I hope that I didnt say something wrong now.

**Comment by DavisMiculis** [comment]
@LittleSatan Are you suggesting something like:
```js
this.rand = new Phaser.RandomDataGenerator(['1234'])

function my_random() {
  return this.rand.normal;
}

this simplex. = new SimplexNoise(my_random);
```
?

**Comment by jwagner** [comment]
@LittleSatan No worries. I appreciate the intent to help, even if it turned out to be a non issue. :)
@DavisMiculis is it possible that you need to bind this.rand.normal?
```js
new SimplexNoise(this.rand.normal.bind(this.rand))
```
If you just pass this.rand.normal the 'this value' will usually not be bound correctly.

**Comment by DavisMiculis** [comment]
@jwagner oh, I forgot about `.bind`, will try later, and comment on result.

**Comment by jwagner** [comment]
I assume this solved your problem. ;)
