### ISSUE TITLE
Option to make the noise wrap

### ISSUE THREAD

**Issue by arcanis** [jwagner/simplex-noise.js#22]
I'm still searching for documentation on the subject since there isn't much and it's quite scattered, but it seems like making tileable noises is a non-trivial problem. It could be interesting to implement this directly into the library.

**Comment by jwagner** [comment]
The usual hacky solution is to just blend the edges, but I guess it would be nicer to just adapt the algorithm to wrap the domain of the noise functions.

https://www.gamedev.net/blogs/entry/2138456-seamless-noise/ is another way that uses 4 dimensional noise to do the wrapping. I hope that helps.
