### ISSUE TITLE
SimplexNoise is undefined in webworkers

### ISSUE THREAD

**Issue by kosshi-net** [jwagner/simplex-noise.js#24]
Just calling ``importScripts()`` does not bring SimplexNoise to the global scope in webworkers. This at least used to work with earlier versions.

Workaround:
```js
let exports = {};
importScripts('simplex-noise.js');
let SimplexNoise = exports.SimplexNoise;
```

**Comment by jwagner** [comment]
This should be resolved by using es modules now.  https://web.dev/module-workers/
