### ISSUE TITLE
`package.json` not exported for Sapper

### ISSUE THREAD

**Issue by EvasiveXkiller** [jwagner/simplex-noise.js#40]
Whenever I build `dev` or `build` in [sapper](https://sapper.svelte.dev/), `rollup-plugin-svelte` shows this warning.

```shell
[rollup-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.
```

Just to bring this to your attention, everything still works even though the warning is shown. All builds still are successful and functionality is not affected.

**Comment by jwagner** [comment]
Hi @EvasiveXkiller , Thanks for the heads up. Are you aware of any specs that say package.json should be exposed? I'm not aware of any other bundler requiring this

**Comment by EvasiveXkiller** [comment]
After some digging around, I think this issue is just specific to `rollup-plugin-svelte`. Since this package is not exporting any svelte components and basing on [this](https://github.com/sveltejs/rollup-plugin-svelte#pkgsvelte), its probably fine to just ignore this warning.

**Comment by jwagner** [comment]
Thanks for the update @EvasiveXkiller . I'll close this issue for now. If it turns out that this is a problem for anyone just let me know and we can reopen it. :)
