### ISSUE TITLE
Uncaught TypeError: SimplexNoise is not a constructor

### ISSUE THREAD

**Issue by twentytwo777** [jwagner/simplex-noise.js#52]
I have problem.

**Comment by jwagner** [comment]
Hi @twentytwo777, There is very little information in this issue to replicate your problem but it looks like you are using the 3.x API while having 4.x installed. If that's the case please read [Migrating from 3.x to 4.x](https://github.com/jwagner/simplex-noise.js#migrating-from-3x-to-4x), that should help.

**Comment by twentytwo777** [comment]
I read this, but I would like to know if the CDN is still unchanged? Or is there another import link without nodejs.

**Comment by twentytwo777** [comment]
Thanks!
