### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by Aaron193** [jwagner/simplex-noise.js#62]
Under the section called "Initialization with a seed", it looks like the function call Alea('seed') should be alea('seed') instead.

import { createNoise2D } from 'simplex-noise';
import alea from 'alea';
const noise2D = createNoise2D(Alea('seed')); // this line
const value2d = noise2D(x, y);

**Comment by jwagner** [comment]
Alea for some reason capitalizes the export: https://github.com/coverslide/node-alea/blob/master/index.d.ts
But you are totally right, the import is lower case, functions should be lower case anyways, so the call should be lower case as well. :)

**Comment by jwagner** [comment]
Fixed in c3ff2195a0cb1d6fa2d0c77cc2a4410bd2d5acf6, thanks for the report!
